# Generated by Django 2.1.1 on 2018-10-07 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad_de_extension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.CharField(max_length=60)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('presupuesto', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Antecedente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enfermedad', models.CharField(max_length=60)),
                ('fecha_aparicion', models.DateField()),
                ('medicamento', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('apellido', models.CharField(max_length=60)),
                ('tipo_documento', models.IntegerField(default=0)),
                ('documento', models.IntegerField(choices=[(-1, 'Documento Único'), (0, 'Libreta de Enrolamiento'), (1, 'Libreta Cívica')], default=-1)),
                ('sexo', models.CharField(max_length=1)),
                ('fecha_de_nacimiento', models.DateField()),
                ('telefono', models.IntegerField()),
                ('numero_asociado', models.IntegerField()),
                ('antecedente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sosjujuy.Antecedente')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Derivacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('motivo', models.CharField(max_length=300)),
                ('observacion', models.CharField(max_length=300)),
                ('beneficiario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sosjujuy.Beneficiario')),
            ],
        ),
        migrations.CreateModel(
            name='Disponibilidad_horaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_de_la_semana', models.IntegerField(choices=[(-1, '-'), (0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], default=-1)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(max_length=60)),
                ('barrio', models.CharField(max_length=60)),
                ('calle', models.CharField(max_length=60)),
                ('numero', models.IntegerField()),
                ('observaciones', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Prestacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rubro', models.IntegerField(choices=[(-1, '-'), (0, 'Odontología'), (1, 'Clases de Inglés'), (2, 'Psicología')], default=-1)),
                ('porcentaje_de_cobertura', models.IntegerField()),
                ('descripcion', models.CharField(max_length=300)),
                ('condiciones_de_prestacion', models.CharField(max_length=300)),
                ('aclaraciones', models.CharField(max_length=300)),
                ('dias_disponibles', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sosjujuy.Disponibilidad_horaria')),
                ('domicilio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sosjujuy.Domicilio')),
            ],
        ),
        migrations.CreateModel(
            name='Prestador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('apellido', models.CharField(max_length=60)),
                ('tipo_documento', models.IntegerField(default=0)),
                ('documento', models.IntegerField(choices=[(-1, 'Documento Único'), (0, 'Libreta de Enrolamiento'), (1, 'Libreta Cívica')], default=-1)),
                ('sexo', models.CharField(max_length=1)),
                ('fecha_de_nacimiento', models.DateField()),
                ('telefono', models.IntegerField()),
                ('matricula', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sosjujuy.Pais')),
            ],
        ),
        migrations.AddField(
            model_name='prestacion',
            name='prestador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sosjujuy.Prestador'),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='pais',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sosjujuy.Pais'),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='provincia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sosjujuy.Provincia'),
        ),
        migrations.AddField(
            model_name='derivacion',
            name='prestacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sosjujuy.Prestacion'),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='domicilio_legal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domicilio_legal', to='sosjujuy.Domicilio'),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='domicilio_real',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domicilio_real', to='sosjujuy.Domicilio'),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='familiar',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sosjujuy.Beneficiario'),
        ),
        migrations.AddField(
            model_name='actividad_de_extension',
            name='dias_disponibles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sosjujuy.Disponibilidad_horaria'),
        ),
        migrations.AddField(
            model_name='actividad_de_extension',
            name='encargado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sosjujuy.Prestador'),
        ),
    ]
