# Generated by Django 2.1.1 on 2018-10-16 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sosjujuy', '0002_auto_20181007_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestacion',
            name='rubro',
            field=models.CharField(max_length=300),
        ),
    ]
