# Generated by Django 2.1.1 on 2018-10-16 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sosjujuy', '0003_auto_20181016_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='derivacion',
            name='fecha_hora',
            field=models.DateTimeField(null=True),
        ),
    ]
