# Generated by Django 2.1.1 on 2018-11-12 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sosjujuy', '0007_beneficiario_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiario',
            name='telefono',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='prestador',
            name='telefono',
            field=models.CharField(max_length=15),
        ),
    ]
