# Generated by Django 2.1.1 on 2018-11-13 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sosjujuy', '0008_auto_20181112_2021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beneficiario',
            old_name='numero_asociado',
            new_name='numero_beneficiario',
        ),
        migrations.AddField(
            model_name='prestador',
            name='especialidad',
            field=models.CharField(default='Odontologia', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='telefono',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='prestador',
            name='telefono',
            field=models.CharField(max_length=16),
        ),
    ]
