# Generated by Django 2.1 on 2019-12-15 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sosjujuy', '0011_auto_20191209_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiario',
            name='id',
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='numero_beneficiario',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
