# Generated by Django 2.1 on 2019-12-18 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sosjujuy', '0014_auto_20191217_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestacion',
            name='domicilio',
        ),
    ]
