# Generated by Django 2.1 on 2019-12-18 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sosjujuy', '0015_remove_prestacion_domicilio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escala', models.CharField(max_length=300)),
                ('escalaDos', models.CharField(max_length=300)),
                ('asunto', models.CharField(max_length=300)),
                ('estado', models.CharField(max_length=300)),
                ('fecha', models.DateField()),
            ],
        ),
    ]
