# Generated by Django 2.1 on 2019-12-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sosjujuy', '0017_auto_20191218_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='archivo',
            field=models.FileField(max_length=254, null=True, upload_to=None),
        ),
    ]
