# Generated by Django 2.1 on 2019-12-19 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sosjujuy', '0018_notificacion_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='archivo',
            field=models.FileField(max_length=254, null=True, upload_to=''),
        ),
    ]
