# Generated by Django 2.1 on 2019-12-19 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sosjujuy', '0019_auto_20191219_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='beneficiario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sosjujuy.Beneficiario'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='prestador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sosjujuy.Prestador'),
        ),
    ]
