# Generated by Django 2.1 on 2019-12-20 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sosjujuy', '0020_auto_20191219_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='observacion',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='domicilio',
            name='departamento',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='domicilio',
            name='piso',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
