# Generated by Django 2.1 on 2019-12-23 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sosjujuy', '0022_auto_20191222_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionEstado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=300)),
                ('observacion', models.CharField(default='', max_length=500)),
                ('archivo', models.FileField(blank=True, max_length=254, null=True, upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='archivo',
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='observacion',
        ),
        migrations.AddField(
            model_name='notificacionestado',
            name='notificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sosjujuy.Notificacion'),
        ),
    ]
