# Generated by Django 2.1 on 2019-12-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sosjujuy', '0023_auto_20191223_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacionestado',
            name='observacion',
            field=models.CharField(max_length=500),
        ),
    ]
