# Generated by Django 2.1 on 2019-12-27 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sosjujuy', '0025_notificacionestado_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestacion',
            name='domicilio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sosjujuy.Domicilio'),
        ),
        migrations.AlterField(
            model_name='domicilio',
            name='observaciones',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
