# Generated by Django 2.1 on 2019-12-28 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sosjujuy', '0028_notificacionestado_fecha'),
        ('sosjujuy', '0011_auto_20191219_2043'),
    ]

    operations = [
    ]
