# Generated by Django 2.1 on 2020-01-03 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sosjujuy', '0029_merge_20191228_0337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aulas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=160)),
                ('ubicacion', models.CharField(choices=[('', '----------'), ('Interna', 'Interna'), ('Externa', 'Externa')], max_length=60)),
                ('estado', models.CharField(choices=[('', '----------'), ('Nueva', 'Nueva'), ('Habilitada', 'Habilitada'), ('Ocupada', 'Ocupada'), ('Libre', 'Libre'), ('Deshabilitada', 'Deshabilitada')], max_length=60)),
                ('capacidad', models.IntegerField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
