# Generated by Django 2.1 on 2020-01-03 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sosjujuy', '0030_aulas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aulas',
            new_name='Aula',
        ),
    ]
